//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public System.DateTime lastenter { get; set; }
        public string ip { get; set; }
        public Nullable<int> services1 { get; set; }
        public Nullable<int> services2 { get; set; }
        public Nullable<int> services3 { get; set; }
        public Nullable<int> services4 { get; set; }
        public Nullable<int> services5 { get; set; }
        public int type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual Services Services { get; set; }
        public virtual Services Services6 { get; set; }
        public virtual Services Services7 { get; set; }
        public virtual Services Services8 { get; set; }
        public virtual Services Services9 { get; set; }
        public virtual Type Type1 { get; set; }
    }
}
