//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public System.DateTime createDate { get; set; }
        public int code_services1 { get; set; }
        public Nullable<int> code_services2 { get; set; }
        public Nullable<int> code_services3 { get; set; }
        public Nullable<int> code_services4 { get; set; }
        public Nullable<int> code_services5 { get; set; }
        public bool order_status { get; set; }
        public bool service_status { get; set; }
        public int due_time { get; set; }
        public int user_id { get; set; }
        public int patient_id { get; set; }
        public long barcode { get; set; }
    
        public virtual Patients Patients { get; set; }
        public virtual Services Services { get; set; }
        public virtual Services Services1 { get; set; }
        public virtual Services Services2 { get; set; }
        public virtual Services Services3 { get; set; }
        public virtual Services Services4 { get; set; }
        public virtual Users Users { get; set; }
    }
}
