//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patients()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string fullName { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public long passport_data { get; set; }
        public string email { get; set; }
        public long insurance_number { get; set; }
        public string insurance_type { get; set; }
        public int insurance_company_ID { get; set; }
    
        public virtual Insurance_companes Insurance_companes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
